// Charitable Deductions Calculator 2025 - Item Catalog
// Values based on fair market value guides for items in excellent condition
// Raw format: "X" (fixed), "A-B" (range), "X+" (minimum plus)

export interface DonationItem {
  cat: string;
  item: string;
  raw: string;
}

export const ITEMS: DonationItem[] = [
  // Men's Clothing
  { cat: "Men's Clothing", item: "Suit (2-piece)", raw: "25-75" },
  { cat: "Men's Clothing", item: "Sport Coat/Blazer", raw: "15-45" },
  { cat: "Men's Clothing", item: "Dress Pants", raw: "6-12" },
  { cat: "Men's Clothing", item: "Jeans", raw: "6-18" },
  { cat: "Men's Clothing", item: "Casual Pants/Khakis", raw: "5-12" },
  { cat: "Men's Clothing", item: "Dress Shirt", raw: "4-12" },
  { cat: "Men's Clothing", item: "Casual Shirt", raw: "4-9" },
  { cat: "Men's Clothing", item: "T-Shirt", raw: "2-6" },
  { cat: "Men's Clothing", item: "Polo Shirt", raw: "4-10" },
  { cat: "Men's Clothing", item: "Sweater", raw: "6-15" },
  { cat: "Men's Clothing", item: "Sweatshirt/Hoodie", raw: "5-12" },
  { cat: "Men's Clothing", item: "Winter Coat", raw: "20-75" },
  { cat: "Men's Clothing", item: "Light Jacket", raw: "10-25" },
  { cat: "Men's Clothing", item: "Raincoat", raw: "10-30" },
  { cat: "Men's Clothing", item: "Vest", raw: "5-12" },
  { cat: "Men's Clothing", item: "Shorts", raw: "4-10" },
  { cat: "Men's Clothing", item: "Swimsuit", raw: "4-10" },
  { cat: "Men's Clothing", item: "Pajamas", raw: "4-10" },
  { cat: "Men's Clothing", item: "Robe", raw: "6-15" },
  { cat: "Men's Clothing", item: "Underwear (new, pack)", raw: "5+" },
  { cat: "Men's Clothing", item: "Socks (pair)", raw: "1-3" },
  { cat: "Men's Clothing", item: "Tie", raw: "3-10" },
  { cat: "Men's Clothing", item: "Belt", raw: "4-12" },
  { cat: "Men's Clothing", item: "Dress Shoes", raw: "15-40" },
  { cat: "Men's Clothing", item: "Casual Shoes", raw: "10-25" },
  { cat: "Men's Clothing", item: "Athletic Shoes", raw: "15-40" },
  { cat: "Men's Clothing", item: "Boots", raw: "15-50" },
  { cat: "Men's Clothing", item: "Sandals", raw: "5-15" },
  { cat: "Men's Clothing", item: "Hat/Cap", raw: "3-10" },
  { cat: "Men's Clothing", item: "Gloves", raw: "4-10" },
  { cat: "Men's Clothing", item: "Scarf", raw: "4-12" },

  // Women's Clothing
  { cat: "Women's Clothing", item: "Dress (casual)", raw: "8-20" },
  { cat: "Women's Clothing", item: "Dress (formal/evening)", raw: "20-100" },
  { cat: "Women's Clothing", item: "Suit (2-piece)", raw: "25-75" },
  { cat: "Women's Clothing", item: "Blazer/Jacket", raw: "12-35" },
  { cat: "Women's Clothing", item: "Skirt", raw: "5-15" },
  { cat: "Women's Clothing", item: "Dress Pants", raw: "6-15" },
  { cat: "Women's Clothing", item: "Jeans", raw: "6-20" },
  { cat: "Women's Clothing", item: "Casual Pants", raw: "5-12" },
  { cat: "Women's Clothing", item: "Leggings", raw: "4-12" },
  { cat: "Women's Clothing", item: "Blouse", raw: "5-15" },
  { cat: "Women's Clothing", item: "Casual Top", raw: "4-10" },
  { cat: "Women's Clothing", item: "T-Shirt", raw: "2-6" },
  { cat: "Women's Clothing", item: "Sweater", raw: "6-18" },
  { cat: "Women's Clothing", item: "Cardigan", raw: "6-15" },
  { cat: "Women's Clothing", item: "Sweatshirt/Hoodie", raw: "5-12" },
  { cat: "Women's Clothing", item: "Winter Coat", raw: "25-100" },
  { cat: "Women's Clothing", item: "Light Jacket", raw: "10-30" },
  { cat: "Women's Clothing", item: "Raincoat", raw: "10-30" },
  { cat: "Women's Clothing", item: "Vest", raw: "5-15" },
  { cat: "Women's Clothing", item: "Shorts", raw: "4-10" },
  { cat: "Women's Clothing", item: "Swimsuit", raw: "8-20" },
  { cat: "Women's Clothing", item: "Pajamas", raw: "5-12" },
  { cat: "Women's Clothing", item: "Robe", raw: "8-20" },
  { cat: "Women's Clothing", item: "Underwear (new, pack)", raw: "5+" },
  { cat: "Women's Clothing", item: "Socks/Hosiery (pair)", raw: "1-4" },
  { cat: "Women's Clothing", item: "Bra (new)", raw: "5+" },
  { cat: "Women's Clothing", item: "Belt", raw: "4-12" },
  { cat: "Women's Clothing", item: "Scarf", raw: "5-15" },
  { cat: "Women's Clothing", item: "Dress Shoes/Heels", raw: "12-40" },
  { cat: "Women's Clothing", item: "Casual Shoes/Flats", raw: "8-25" },
  { cat: "Women's Clothing", item: "Athletic Shoes", raw: "15-40" },
  { cat: "Women's Clothing", item: "Boots", raw: "15-60" },
  { cat: "Women's Clothing", item: "Sandals", raw: "5-18" },
  { cat: "Women's Clothing", item: "Handbag/Purse", raw: "10-50" },
  { cat: "Women's Clothing", item: "Designer Handbag", raw: "50+" },
  { cat: "Women's Clothing", item: "Hat", raw: "4-12" },
  { cat: "Women's Clothing", item: "Gloves", raw: "4-12" },

  // Children's Clothing
  { cat: "Children's Clothing", item: "Dress", raw: "4-12" },
  { cat: "Children's Clothing", item: "Suit/Formal Wear", raw: "8-20" },
  { cat: "Children's Clothing", item: "Pants/Jeans", raw: "3-10" },
  { cat: "Children's Clothing", item: "Shorts", raw: "2-6" },
  { cat: "Children's Clothing", item: "Shirt", raw: "2-6" },
  { cat: "Children's Clothing", item: "T-Shirt", raw: "1-4" },
  { cat: "Children's Clothing", item: "Sweater", raw: "3-10" },
  { cat: "Children's Clothing", item: "Sweatshirt/Hoodie", raw: "3-8" },
  { cat: "Children's Clothing", item: "Winter Coat", raw: "10-30" },
  { cat: "Children's Clothing", item: "Light Jacket", raw: "5-15" },
  { cat: "Children's Clothing", item: "Pajamas", raw: "3-8" },
  { cat: "Children's Clothing", item: "Swimsuit", raw: "3-8" },
  { cat: "Children's Clothing", item: "Shoes", raw: "5-15" },
  { cat: "Children's Clothing", item: "Boots", raw: "8-20" },
  { cat: "Children's Clothing", item: "Socks (pair)", raw: "1-2" },
  { cat: "Children's Clothing", item: "Hat/Cap", raw: "2-6" },
  { cat: "Children's Clothing", item: "Gloves/Mittens", raw: "2-6" },

  // Baby Items
  { cat: "Baby Items", item: "Onesie", raw: "1-4" },
  { cat: "Baby Items", item: "Outfit Set", raw: "3-10" },
  { cat: "Baby Items", item: "Sleeper/Pajamas", raw: "2-6" },
  { cat: "Baby Items", item: "Jacket/Coat", raw: "5-15" },
  { cat: "Baby Items", item: "Shoes/Booties", raw: "2-8" },
  { cat: "Baby Items", item: "Hat", raw: "1-4" },
  { cat: "Baby Items", item: "Blanket", raw: "3-10" },
  { cat: "Baby Items", item: "Crib", raw: "50-150" },
  { cat: "Baby Items", item: "Bassinet", raw: "25-75" },
  { cat: "Baby Items", item: "High Chair", raw: "20-60" },
  { cat: "Baby Items", item: "Stroller", raw: "30-100" },
  { cat: "Baby Items", item: "Car Seat", raw: "25-75" },
  { cat: "Baby Items", item: "Playpen/Pack n Play", raw: "20-50" },
  { cat: "Baby Items", item: "Swing", raw: "15-40" },
  { cat: "Baby Items", item: "Bouncer", raw: "10-30" },
  { cat: "Baby Items", item: "Baby Monitor", raw: "15-40" },
  { cat: "Baby Items", item: "Diaper Bag", raw: "8-25" },
  { cat: "Baby Items", item: "Changing Table", raw: "30-75" },
  { cat: "Baby Items", item: "Baby Bathtub", raw: "5-15" },
  { cat: "Baby Items", item: "Nursing Pillow", raw: "8-20" },
  { cat: "Baby Items", item: "Baby Carrier/Wrap", raw: "15-40" },

  // Furniture - Living Room
  { cat: "Furniture - Living Room", item: "Sofa (3-seat)", raw: "75-300" },
  { cat: "Furniture - Living Room", item: "Loveseat", raw: "50-200" },
  { cat: "Furniture - Living Room", item: "Sectional Sofa", raw: "150-500" },
  { cat: "Furniture - Living Room", item: "Recliner", raw: "50-175" },
  { cat: "Furniture - Living Room", item: "Armchair", raw: "30-125" },
  { cat: "Furniture - Living Room", item: "Ottoman", raw: "15-50" },
  { cat: "Furniture - Living Room", item: "Coffee Table", raw: "25-100" },
  { cat: "Furniture - Living Room", item: "End Table", raw: "15-50" },
  { cat: "Furniture - Living Room", item: "Console Table", raw: "25-100" },
  { cat: "Furniture - Living Room", item: "Entertainment Center", raw: "50-200" },
  { cat: "Furniture - Living Room", item: "TV Stand", raw: "25-100" },
  { cat: "Furniture - Living Room", item: "Bookshelf", raw: "25-100" },
  { cat: "Furniture - Living Room", item: "Floor Lamp", raw: "15-50" },
  { cat: "Furniture - Living Room", item: "Table Lamp", raw: "10-35" },
  { cat: "Furniture - Living Room", item: "Area Rug (small)", raw: "20-75" },
  { cat: "Furniture - Living Room", item: "Area Rug (large)", raw: "50-200" },

  // Furniture - Bedroom
  { cat: "Furniture - Bedroom", item: "Bed Frame (King)", raw: "75-250" },
  { cat: "Furniture - Bedroom", item: "Bed Frame (Queen)", raw: "60-200" },
  { cat: "Furniture - Bedroom", item: "Bed Frame (Full)", raw: "50-150" },
  { cat: "Furniture - Bedroom", item: "Bed Frame (Twin)", raw: "30-100" },
  { cat: "Furniture - Bedroom", item: "Mattress (King)", raw: "100-300" },
  { cat: "Furniture - Bedroom", item: "Mattress (Queen)", raw: "75-250" },
  { cat: "Furniture - Bedroom", item: "Mattress (Full)", raw: "50-175" },
  { cat: "Furniture - Bedroom", item: "Mattress (Twin)", raw: "35-100" },
  { cat: "Furniture - Bedroom", item: "Dresser (large)", raw: "50-200" },
  { cat: "Furniture - Bedroom", item: "Dresser (small)", raw: "30-100" },
  { cat: "Furniture - Bedroom", item: "Chest of Drawers", raw: "40-125" },
  { cat: "Furniture - Bedroom", item: "Nightstand", raw: "15-50" },
  { cat: "Furniture - Bedroom", item: "Wardrobe/Armoire", raw: "75-250" },
  { cat: "Furniture - Bedroom", item: "Vanity with Mirror", raw: "40-125" },
  { cat: "Furniture - Bedroom", item: "Headboard", raw: "30-125" },

  // Furniture - Dining
  { cat: "Furniture - Dining", item: "Dining Table (seats 6+)", raw: "75-300" },
  { cat: "Furniture - Dining", item: "Dining Table (seats 4)", raw: "50-175" },
  { cat: "Furniture - Dining", item: "Dining Chair", raw: "15-50" },
  { cat: "Furniture - Dining", item: "China Cabinet", raw: "75-250" },
  { cat: "Furniture - Dining", item: "Buffet/Sideboard", raw: "50-175" },
  { cat: "Furniture - Dining", item: "Bar Stool", raw: "15-50" },
  { cat: "Furniture - Dining", item: "Kitchen Table", raw: "30-100" },

  // Furniture - Office
  { cat: "Furniture - Office", item: "Desk (large)", raw: "50-200" },
  { cat: "Furniture - Office", item: "Desk (small)", raw: "30-100" },
  { cat: "Furniture - Office", item: "Office Chair", raw: "25-100" },
  { cat: "Furniture - Office", item: "Filing Cabinet (2-drawer)", raw: "20-60" },
  { cat: "Furniture - Office", item: "Filing Cabinet (4-drawer)", raw: "30-100" },
  { cat: "Furniture - Office", item: "Bookcase", raw: "25-100" },
  { cat: "Furniture - Office", item: "Computer Desk", raw: "30-125" },

  // Kitchen Appliances
  { cat: "Kitchen Appliances", item: "Refrigerator", raw: "150-400" },
  { cat: "Kitchen Appliances", item: "Stove/Range", raw: "100-300" },
  { cat: "Kitchen Appliances", item: "Microwave", raw: "20-75" },
  { cat: "Kitchen Appliances", item: "Dishwasher", raw: "75-200" },
  { cat: "Kitchen Appliances", item: "Toaster Oven", raw: "15-50" },
  { cat: "Kitchen Appliances", item: "Toaster", raw: "8-25" },
  { cat: "Kitchen Appliances", item: "Coffee Maker (drip)", raw: "10-35" },
  { cat: "Kitchen Appliances", item: "Coffee Maker (espresso)", raw: "50-200" },
  { cat: "Kitchen Appliances", item: "Keurig/Pod Coffee Maker", raw: "25-75" },
  { cat: "Kitchen Appliances", item: "Blender", raw: "15-50" },
  { cat: "Kitchen Appliances", item: "Food Processor", raw: "25-75" },
  { cat: "Kitchen Appliances", item: "Stand Mixer", raw: "75-200" },
  { cat: "Kitchen Appliances", item: "Hand Mixer", raw: "10-30" },
  { cat: "Kitchen Appliances", item: "Slow Cooker/Crock Pot", raw: "10-35" },
  { cat: "Kitchen Appliances", item: "Instant Pot/Pressure Cooker", raw: "30-75" },
  { cat: "Kitchen Appliances", item: "Air Fryer", raw: "25-75" },
  { cat: "Kitchen Appliances", item: "Rice Cooker", raw: "15-40" },
  { cat: "Kitchen Appliances", item: "Electric Kettle", raw: "10-30" },
  { cat: "Kitchen Appliances", item: "Waffle Maker", raw: "10-30" },
  { cat: "Kitchen Appliances", item: "Griddle", raw: "15-40" },
  { cat: "Kitchen Appliances", item: "Electric Grill", raw: "20-60" },
  { cat: "Kitchen Appliances", item: "Juicer", raw: "25-75" },
  { cat: "Kitchen Appliances", item: "Bread Maker", raw: "25-75" },
  { cat: "Kitchen Appliances", item: "Ice Cream Maker", raw: "20-50" },

  // Kitchenware
  { cat: "Kitchenware", item: "Pot/Pan Set", raw: "30-100" },
  { cat: "Kitchenware", item: "Individual Pot", raw: "8-25" },
  { cat: "Kitchenware", item: "Individual Pan", raw: "8-25" },
  { cat: "Kitchenware", item: "Baking Sheet", raw: "3-10" },
  { cat: "Kitchenware", item: "Baking Dish", raw: "5-15" },
  { cat: "Kitchenware", item: "Mixing Bowl Set", raw: "8-25" },
  { cat: "Kitchenware", item: "Knife Set", raw: "20-75" },
  { cat: "Kitchenware", item: "Individual Knife", raw: "5-20" },
  { cat: "Kitchenware", item: "Cutting Board", raw: "5-20" },
  { cat: "Kitchenware", item: "Utensil Set", raw: "10-30" },
  { cat: "Kitchenware", item: "Dinnerware Set (service for 4)", raw: "20-75" },
  { cat: "Kitchenware", item: "Dinnerware Set (service for 8)", raw: "40-125" },
  { cat: "Kitchenware", item: "Glassware Set", raw: "10-35" },
  { cat: "Kitchenware", item: "Flatware Set", raw: "15-50" },
  { cat: "Kitchenware", item: "Serving Platter", raw: "8-25" },
  { cat: "Kitchenware", item: "Serving Bowl", raw: "5-20" },
  { cat: "Kitchenware", item: "Pitcher", raw: "5-15" },
  { cat: "Kitchenware", item: "Storage Container Set", raw: "10-30" },
  { cat: "Kitchenware", item: "Mug", raw: "2-6" },
  { cat: "Kitchenware", item: "Wine Glasses (set of 4)", raw: "10-30" },

  // Electronics
  { cat: "Electronics", item: "Television (55\"+)", raw: "150-400" },
  { cat: "Electronics", item: "Television (40-54\")", raw: "75-200" },
  { cat: "Electronics", item: "Television (under 40\")", raw: "40-125" },
  { cat: "Electronics", item: "Computer Monitor", raw: "30-100" },
  { cat: "Electronics", item: "Desktop Computer", raw: "100-400" },
  { cat: "Electronics", item: "Laptop Computer", raw: "100-500" },
  { cat: "Electronics", item: "Tablet", raw: "50-250" },
  { cat: "Electronics", item: "E-Reader", raw: "25-75" },
  { cat: "Electronics", item: "Printer", raw: "25-100" },
  { cat: "Electronics", item: "Scanner", raw: "25-75" },
  { cat: "Electronics", item: "All-in-One Printer", raw: "40-125" },
  { cat: "Electronics", item: "Keyboard", raw: "10-40" },
  { cat: "Electronics", item: "Mouse", raw: "5-25" },
  { cat: "Electronics", item: "Webcam", raw: "15-50" },
  { cat: "Electronics", item: "Speakers (pair)", raw: "20-100" },
  { cat: "Electronics", item: "Soundbar", raw: "40-150" },
  { cat: "Electronics", item: "Headphones (over-ear)", raw: "25-100" },
  { cat: "Electronics", item: "Earbuds", raw: "15-75" },
  { cat: "Electronics", item: "Bluetooth Speaker", raw: "20-75" },
  { cat: "Electronics", item: "DVD/Blu-ray Player", raw: "15-50" },
  { cat: "Electronics", item: "Streaming Device", raw: "15-50" },
  { cat: "Electronics", item: "Gaming Console", raw: "100-300" },
  { cat: "Electronics", item: "Video Game", raw: "5-30" },
  { cat: "Electronics", item: "Router/Modem", raw: "20-75" },
  { cat: "Electronics", item: "External Hard Drive", raw: "25-75" },
  { cat: "Electronics", item: "USB Flash Drive", raw: "5-15" },
  { cat: "Electronics", item: "Camera (DSLR)", raw: "150-500" },
  { cat: "Electronics", item: "Camera (Point & Shoot)", raw: "30-100" },
  { cat: "Electronics", item: "Camcorder", raw: "50-175" },
  { cat: "Electronics", item: "Tripod", raw: "15-50" },

  // Linens & Bedding
  { cat: "Linens & Bedding", item: "Comforter/Duvet (King)", raw: "25-75" },
  { cat: "Linens & Bedding", item: "Comforter/Duvet (Queen)", raw: "20-60" },
  { cat: "Linens & Bedding", item: "Comforter/Duvet (Full/Twin)", raw: "15-50" },
  { cat: "Linens & Bedding", item: "Sheet Set (King)", raw: "15-50" },
  { cat: "Linens & Bedding", item: "Sheet Set (Queen)", raw: "12-40" },
  { cat: "Linens & Bedding", item: "Sheet Set (Full/Twin)", raw: "10-30" },
  { cat: "Linens & Bedding", item: "Pillow", raw: "5-20" },
  { cat: "Linens & Bedding", item: "Pillowcase Set", raw: "5-15" },
  { cat: "Linens & Bedding", item: "Blanket/Throw", raw: "8-30" },
  { cat: "Linens & Bedding", item: "Quilt", raw: "20-75" },
  { cat: "Linens & Bedding", item: "Mattress Pad", raw: "15-50" },
  { cat: "Linens & Bedding", item: "Bed Skirt", raw: "8-25" },
  { cat: "Linens & Bedding", item: "Bath Towel", raw: "3-10" },
  { cat: "Linens & Bedding", item: "Hand Towel", raw: "2-6" },
  { cat: "Linens & Bedding", item: "Washcloth", raw: "1-3" },
  { cat: "Linens & Bedding", item: "Bath Mat", raw: "5-15" },
  { cat: "Linens & Bedding", item: "Shower Curtain", raw: "5-20" },
  { cat: "Linens & Bedding", item: "Table Linens Set", raw: "10-35" },
  { cat: "Linens & Bedding", item: "Kitchen Towels (set)", raw: "5-15" },
  { cat: "Linens & Bedding", item: "Curtains/Drapes (pair)", raw: "15-50" },

  // Home Decor
  { cat: "Home Decor", item: "Wall Art/Painting (large)", raw: "25-100" },
  { cat: "Home Decor", item: "Wall Art/Painting (small)", raw: "10-40" },
  { cat: "Home Decor", item: "Picture Frame", raw: "5-25" },
  { cat: "Home Decor", item: "Mirror (large)", raw: "25-100" },
  { cat: "Home Decor", item: "Mirror (small)", raw: "10-40" },
  { cat: "Home Decor", item: "Vase", raw: "5-25" },
  { cat: "Home Decor", item: "Decorative Bowl", raw: "5-20" },
  { cat: "Home Decor", item: "Candle Holder", raw: "5-20" },
  { cat: "Home Decor", item: "Clock (wall)", raw: "10-40" },
  { cat: "Home Decor", item: "Clock (tabletop)", raw: "8-25" },
  { cat: "Home Decor", item: "Decorative Pillow", raw: "5-20" },
  { cat: "Home Decor", item: "Artificial Plant/Flowers", raw: "8-30" },
  { cat: "Home Decor", item: "Sculpture/Figurine", raw: "10-50" },
  { cat: "Home Decor", item: "Basket", raw: "5-20" },

  // Outdoor & Garden
  { cat: "Outdoor & Garden", item: "Patio Table", raw: "40-150" },
  { cat: "Outdoor & Garden", item: "Patio Chair", raw: "20-75" },
  { cat: "Outdoor & Garden", item: "Patio Set (table + chairs)", raw: "100-400" },
  { cat: "Outdoor & Garden", item: "Lounge Chair", raw: "30-100" },
  { cat: "Outdoor & Garden", item: "Patio Umbrella", raw: "25-75" },
  { cat: "Outdoor & Garden", item: "Grill (gas)", raw: "75-250" },
  { cat: "Outdoor & Garden", item: "Grill (charcoal)", raw: "25-100" },
  { cat: "Outdoor & Garden", item: "Lawn Mower (push)", raw: "50-150" },
  { cat: "Outdoor & Garden", item: "Lawn Mower (riding)", raw: "300+" },
  { cat: "Outdoor & Garden", item: "Weed Trimmer", raw: "25-75" },
  { cat: "Outdoor & Garden", item: "Leaf Blower", raw: "25-75" },
  { cat: "Outdoor & Garden", item: "Hedge Trimmer", raw: "25-75" },
  { cat: "Outdoor & Garden", item: "Garden Hose", raw: "10-30" },
  { cat: "Outdoor & Garden", item: "Wheelbarrow", raw: "25-75" },
  { cat: "Outdoor & Garden", item: "Garden Tools Set", raw: "20-60" },
  { cat: "Outdoor & Garden", item: "Planters/Pots (each)", raw: "5-30" },
  { cat: "Outdoor & Garden", item: "Fire Pit", raw: "40-150" },
  { cat: "Outdoor & Garden", item: "Outdoor Rug", raw: "20-75" },
  { cat: "Outdoor & Garden", item: "Bird Feeder", raw: "10-35" },

  // Sports & Exercise
  { cat: "Sports & Exercise", item: "Treadmill", raw: "200-600" },
  { cat: "Sports & Exercise", item: "Elliptical", raw: "150-500" },
  { cat: "Sports & Exercise", item: "Exercise Bike", raw: "100-400" },
  { cat: "Sports & Exercise", item: "Weight Bench", raw: "50-175" },
  { cat: "Sports & Exercise", item: "Dumbbell Set", raw: "50-200" },
  { cat: "Sports & Exercise", item: "Barbell Set", raw: "75-250" },
  { cat: "Sports & Exercise", item: "Yoga Mat", raw: "10-30" },
  { cat: "Sports & Exercise", item: "Resistance Bands Set", raw: "10-30" },
  { cat: "Sports & Exercise", item: "Jump Rope", raw: "5-15" },
  { cat: "Sports & Exercise", item: "Bicycle (adult)", raw: "75-300" },
  { cat: "Sports & Exercise", item: "Bicycle (child)", raw: "30-100" },
  { cat: "Sports & Exercise", item: "Bicycle Helmet", raw: "15-40" },
  { cat: "Sports & Exercise", item: "Golf Clubs (full set)", raw: "150-500" },
  { cat: "Sports & Exercise", item: "Golf Clubs (individual)", raw: "15-50" },
  { cat: "Sports & Exercise", item: "Golf Bag", raw: "30-100" },
  { cat: "Sports & Exercise", item: "Tennis Racket", raw: "20-75" },
  { cat: "Sports & Exercise", item: "Baseball Glove", raw: "15-50" },
  { cat: "Sports & Exercise", item: "Baseball Bat", raw: "10-40" },
  { cat: "Sports & Exercise", item: "Basketball", raw: "10-30" },
  { cat: "Sports & Exercise", item: "Football", raw: "10-30" },
  { cat: "Sports & Exercise", item: "Soccer Ball", raw: "10-30" },
  { cat: "Sports & Exercise", item: "Skis (pair)", raw: "75-250" },
  { cat: "Sports & Exercise", item: "Ski Boots", raw: "50-150" },
  { cat: "Sports & Exercise", item: "Snowboard", raw: "75-200" },
  { cat: "Sports & Exercise", item: "Ice Skates", raw: "25-75" },
  { cat: "Sports & Exercise", item: "Roller Blades", raw: "25-75" },
  { cat: "Sports & Exercise", item: "Skateboard", raw: "20-60" },
  { cat: "Sports & Exercise", item: "Fishing Rod/Reel", raw: "25-100" },
  { cat: "Sports & Exercise", item: "Tackle Box", raw: "15-50" },
  { cat: "Sports & Exercise", item: "Tent (2-4 person)", raw: "40-125" },
  { cat: "Sports & Exercise", item: "Tent (6+ person)", raw: "75-200" },
  { cat: "Sports & Exercise", item: "Sleeping Bag", raw: "20-75" },
  { cat: "Sports & Exercise", item: "Camping Stove", raw: "25-75" },
  { cat: "Sports & Exercise", item: "Cooler", raw: "15-50" },
  { cat: "Sports & Exercise", item: "Backpack (hiking)", raw: "30-100" },

  // Tools & Hardware
  { cat: "Tools & Hardware", item: "Power Drill", raw: "25-100" },
  { cat: "Tools & Hardware", item: "Circular Saw", raw: "40-125" },
  { cat: "Tools & Hardware", item: "Jigsaw", raw: "30-100" },
  { cat: "Tools & Hardware", item: "Table Saw", raw: "150-400" },
  { cat: "Tools & Hardware", item: "Miter Saw", raw: "100-300" },
  { cat: "Tools & Hardware", item: "Sander", raw: "25-75" },
  { cat: "Tools & Hardware", item: "Router", raw: "50-150" },
  { cat: "Tools & Hardware", item: "Nail Gun", raw: "50-150" },
  { cat: "Tools & Hardware", item: "Air Compressor", raw: "75-250" },
  { cat: "Tools & Hardware", item: "Shop Vacuum", raw: "40-125" },
  { cat: "Tools & Hardware", item: "Tool Box", raw: "25-100" },
  { cat: "Tools & Hardware", item: "Hand Tool Set", raw: "30-100" },
  { cat: "Tools & Hardware", item: "Socket Set", raw: "25-100" },
  { cat: "Tools & Hardware", item: "Wrench Set", raw: "20-75" },
  { cat: "Tools & Hardware", item: "Screwdriver Set", raw: "15-50" },
  { cat: "Tools & Hardware", item: "Hammer", raw: "8-25" },
  { cat: "Tools & Hardware", item: "Level", raw: "10-35" },
  { cat: "Tools & Hardware", item: "Tape Measure", raw: "5-15" },
  { cat: "Tools & Hardware", item: "Ladder (step)", raw: "25-75" },
  { cat: "Tools & Hardware", item: "Ladder (extension)", raw: "75-200" },
  { cat: "Tools & Hardware", item: "Work Light", raw: "15-50" },
  { cat: "Tools & Hardware", item: "Generator", raw: "200+" },

  // Books & Media
  { cat: "Books & Media", item: "Hardcover Book", raw: "3-10" },
  { cat: "Books & Media", item: "Paperback Book", raw: "1-5" },
  { cat: "Books & Media", item: "Textbook", raw: "10-50" },
  { cat: "Books & Media", item: "Coffee Table Book", raw: "10-35" },
  { cat: "Books & Media", item: "DVD", raw: "2-6" },
  { cat: "Books & Media", item: "Blu-ray", raw: "4-12" },
  { cat: "Books & Media", item: "CD", raw: "2-5" },
  { cat: "Books & Media", item: "Vinyl Record", raw: "5-25" },
  { cat: "Books & Media", item: "Board Game", raw: "5-25" },
  { cat: "Books & Media", item: "Puzzle", raw: "3-10" },

  // Toys & Games
  { cat: "Toys & Games", item: "Action Figure", raw: "3-15" },
  { cat: "Toys & Games", item: "Doll", raw: "5-25" },
  { cat: "Toys & Games", item: "Stuffed Animal", raw: "3-12" },
  { cat: "Toys & Games", item: "Building Blocks Set", raw: "10-50" },
  { cat: "Toys & Games", item: "LEGO Set", raw: "15-75" },
  { cat: "Toys & Games", item: "Remote Control Vehicle", raw: "15-60" },
  { cat: "Toys & Games", item: "Play Kitchen", raw: "30-100" },
  { cat: "Toys & Games", item: "Toy Workbench", raw: "20-60" },
  { cat: "Toys & Games", item: "Dollhouse", raw: "30-100" },
  { cat: "Toys & Games", item: "Tricycle", raw: "20-50" },
  { cat: "Toys & Games", item: "Wagon", raw: "20-60" },
  { cat: "Toys & Games", item: "Ride-on Toy", raw: "25-75" },
  { cat: "Toys & Games", item: "Play Set (outdoor)", raw: "100-400" },
  { cat: "Toys & Games", item: "Sandbox", raw: "25-75" },
  { cat: "Toys & Games", item: "Pool (inflatable)", raw: "15-50" },
  { cat: "Toys & Games", item: "Trampoline", raw: "100-300" },

  // Jewelry & Accessories
  { cat: "Jewelry & Accessories", item: "Costume Jewelry (piece)", raw: "3-15" },
  { cat: "Jewelry & Accessories", item: "Watch (fashion)", raw: "15-75" },
  { cat: "Jewelry & Accessories", item: "Watch (designer)", raw: "100+" },
  { cat: "Jewelry & Accessories", item: "Sunglasses", raw: "10-50" },
  { cat: "Jewelry & Accessories", item: "Designer Sunglasses", raw: "50+" },
  { cat: "Jewelry & Accessories", item: "Wallet", raw: "10-40" },
  { cat: "Jewelry & Accessories", item: "Briefcase", raw: "25-100" },
  { cat: "Jewelry & Accessories", item: "Luggage (carry-on)", raw: "30-100" },
  { cat: "Jewelry & Accessories", item: "Luggage (checked)", raw: "50-175" },
  { cat: "Jewelry & Accessories", item: "Luggage Set", raw: "100-300" },
  { cat: "Jewelry & Accessories", item: "Backpack", raw: "15-50" },

  // Household Appliances
  { cat: "Household Appliances", item: "Washer", raw: "150-400" },
  { cat: "Household Appliances", item: "Dryer", raw: "150-400" },
  { cat: "Household Appliances", item: "Vacuum Cleaner (upright)", raw: "40-150" },
  { cat: "Household Appliances", item: "Vacuum Cleaner (robot)", raw: "100-300" },
  { cat: "Household Appliances", item: "Vacuum Cleaner (handheld)", raw: "25-75" },
  { cat: "Household Appliances", item: "Steam Cleaner", raw: "50-150" },
  { cat: "Household Appliances", item: "Iron", raw: "15-40" },
  { cat: "Household Appliances", item: "Ironing Board", raw: "15-40" },
  { cat: "Household Appliances", item: "Sewing Machine", raw: "50-200" },
  { cat: "Household Appliances", item: "Fan (box/oscillating)", raw: "15-40" },
  { cat: "Household Appliances", item: "Fan (tower)", raw: "25-75" },
  { cat: "Household Appliances", item: "Space Heater", raw: "20-60" },
  { cat: "Household Appliances", item: "Air Purifier", raw: "50-175" },
  { cat: "Household Appliances", item: "Humidifier", raw: "25-75" },
  { cat: "Household Appliances", item: "Dehumidifier", raw: "75-200" },
  { cat: "Household Appliances", item: "Air Conditioner (window)", raw: "75-250" },
  { cat: "Household Appliances", item: "Air Conditioner (portable)", raw: "150-400" },

  // Musical Instruments
  { cat: "Musical Instruments", item: "Acoustic Guitar", raw: "75-300" },
  { cat: "Musical Instruments", item: "Electric Guitar", raw: "100-400" },
  { cat: "Musical Instruments", item: "Bass Guitar", raw: "100-350" },
  { cat: "Musical Instruments", item: "Ukulele", raw: "30-100" },
  { cat: "Musical Instruments", item: "Violin", raw: "75-300" },
  { cat: "Musical Instruments", item: "Keyboard/Piano (digital)", raw: "100-400" },
  { cat: "Musical Instruments", item: "Piano (upright)", raw: "500+" },
  { cat: "Musical Instruments", item: "Drum Set", raw: "200-600" },
  { cat: "Musical Instruments", item: "Saxophone", raw: "200-600" },
  { cat: "Musical Instruments", item: "Trumpet", raw: "100-300" },
  { cat: "Musical Instruments", item: "Flute", raw: "75-250" },
  { cat: "Musical Instruments", item: "Clarinet", raw: "100-300" },
  { cat: "Musical Instruments", item: "Amplifier", raw: "50-200" },
  { cat: "Musical Instruments", item: "Guitar Case", raw: "25-75" },
  { cat: "Musical Instruments", item: "Music Stand", raw: "15-40" },

  // Pet Supplies
  { cat: "Pet Supplies", item: "Dog Crate (large)", raw: "40-125" },
  { cat: "Pet Supplies", item: "Dog Crate (medium)", raw: "25-75" },
  { cat: "Pet Supplies", item: "Dog Crate (small)", raw: "15-50" },
  { cat: "Pet Supplies", item: "Dog Bed", raw: "15-60" },
  { cat: "Pet Supplies", item: "Cat Tree/Tower", raw: "30-100" },
  { cat: "Pet Supplies", item: "Pet Carrier", raw: "20-60" },
  { cat: "Pet Supplies", item: "Aquarium (10-20 gal)", raw: "25-75" },
  { cat: "Pet Supplies", item: "Aquarium (30+ gal)", raw: "75-200" },
  { cat: "Pet Supplies", item: "Pet Food/Water Bowl", raw: "5-20" },
  { cat: "Pet Supplies", item: "Pet Toys (each)", raw: "3-12" },
  { cat: "Pet Supplies", item: "Leash", raw: "5-20" },
  { cat: "Pet Supplies", item: "Collar", raw: "5-20" },

  // Art & Craft Supplies
  { cat: "Art & Craft Supplies", item: "Art Easel", raw: "30-100" },
  { cat: "Art & Craft Supplies", item: "Canvas (large)", raw: "10-30" },
  { cat: "Art & Craft Supplies", item: "Canvas (small)", raw: "5-15" },
  { cat: "Art & Craft Supplies", item: "Paint Set", raw: "15-60" },
  { cat: "Art & Craft Supplies", item: "Colored Pencils Set", raw: "10-40" },
  { cat: "Art & Craft Supplies", item: "Markers Set", raw: "10-40" },
  { cat: "Art & Craft Supplies", item: "Drawing Supplies Set", raw: "15-50" },
  { cat: "Art & Craft Supplies", item: "Craft Supplies Lot", raw: "15-50" },
  { cat: "Art & Craft Supplies", item: "Knitting/Crochet Supplies", raw: "15-50" },
  { cat: "Art & Craft Supplies", item: "Scrapbooking Supplies", raw: "20-75" },

  // Miscellaneous
  { cat: "Miscellaneous", item: "Safe (small)", raw: "50-150" },
  { cat: "Miscellaneous", item: "Safe (large)", raw: "100-300" },
  { cat: "Miscellaneous", item: "Picture Album", raw: "5-20" },
  { cat: "Miscellaneous", item: "Christmas Tree (artificial)", raw: "25-100" },
  { cat: "Miscellaneous", item: "Holiday Decorations (lot)", raw: "15-50" },
  { cat: "Miscellaneous", item: "Storage Bins (set)", raw: "15-50" },
  { cat: "Miscellaneous", item: "Folding Table", raw: "20-60" },
  { cat: "Miscellaneous", item: "Folding Chairs (each)", raw: "8-25" },
];

// Get unique categories sorted alphabetically
export function getCategories(): string[] {
  const cats = new Set(ITEMS.map((item) => item.cat));
  return Array.from(cats).sort();
}

// Get items by category
export function getItemsByCategory(category: string): DonationItem[] {
  return ITEMS.filter((item) => item.cat === category);
}

// Group items by category
export function getItemsGroupedByCategory(): Map<string, DonationItem[]> {
  const grouped = new Map<string, DonationItem[]>();
  for (const item of ITEMS) {
    if (!grouped.has(item.cat)) {
      grouped.set(item.cat, []);
    }
    grouped.get(item.cat)!.push(item);
  }
  return grouped;
}
